name: efficient_net_b2
type: "classifier"

backbone:
  pretrained: True
  num_classes: 3
  in_channels: 1

defaults:
  - metrics@metrics.acc: accuracy
  - metrics@metrics.roc_auc: roc_auc
  - metrics@metrics.roc: roc