hydra:
  run: 
    # Set the output directory to be the same as script's directory
    dir: .
  output_subdir: .hydra

defaults:
  - dataset: deeplense_classify
  - model: 'pinn_efficient_net_b2_deeplense_classify'
  - training: default
  - sampling: default
  - _self_

# Global settings
device: 'cuda'
experiment_name: 'pinn_efficient_net_b2_deeplense_classify'
seed: 42
resume_from_run_id: null